apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-mongodb
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mern-mongodb
      metadata: mern-mongodb
  template:
    metadata:
      labels:
        name: mern-mongodb
        metadata: mern-mongodb
    spec:
      containers:
      - name: mern-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mern-mongodb
  namespace: production
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      #nodePort: 30080
  selector:
    name: mern-mongodb
---
